name: 'Common: Lint commit messages'

on:
  workflow_call:

jobs:
  lint-commits:
    runs-on: ubuntu-20.04
    steps:
      - name: "Lint commit messages"
        uses: CleverShuttle/gh-composite-actions/actions/lint-commits@v1.25.0
