name: 'Common: Rebase nonprod onto master'

on:
  workflow_call:

jobs:
  rebase-nonprod:
    runs-on: ubuntu-20.04

    steps:
      - name: "Checkout repository"
        uses: CleverShuttle/gh-composite-actions/actions/rebase-nonprod@v1.22.0
