name: 'Common: Rebase nonProd onto master'

on:
  workflow_call:

jobs:
  rebase-nonprod:
    runs-on: ubuntu-20.04
    steps:
      - name: "Rebase nonProd onto master"
        uses: CleverShuttle/gh-composite-actions/actions/rebase-nonprod@v1.25.0
