name: 'Common: Rebase NONPROD onto master'

on:
  workflow_call:

jobs:
  rebase-nonprod:
    runs-on: ubuntu-20.04
    steps:
      - name: "Rebase NONPROD onto master"
        uses: CleverShuttle/gh-composite-actions/actions/rebase-nonprod@v1.30.5
